### ISSUE TITLE
Use iofree to verify the initialization and connection process defined in the rfc1928 for a SOCKS5 Proxy.

### ISSUE THREAD

**Issue by hongyi-zhao** [guyingbo/iofree#1]
Hi,

On Ubuntu 20.04, I've Tor listening on 127.0.0.1:9050 as a socks5 proxy. I want to check the initialization and connection process of it with iofree when I'm using the proxy for access some websites, say, by curl like following:

`$ curl -v -x socks5://127.0.0.1:9050 http://clients3.google.com/generate_204`

Any hints for this problem?

Regards

**Comment by guyingbo** [comment]
You can use `scapy` to sniff tcp packets and then use `iofree` to parse socks5 protocol:

~~~python
scapy -s your_session
>>> packets = sniff(iface="lo0", filter="port 9050", count=16)
# your session is blocked here, now run curl command:
# curl -v -x socks5://127.0.0.1:9050 http://clients3.google.com/generate_204
>>> packets
<Sniffed: TCP:16 UDP:0 ICMP:0 Other:0>
>>> for i, p in enumerate(packets):
...:     if hasattr(p, 'load'):
...:         print(i, p.load)
...:
4 b'\x05\x02\x00\x01'
6 b'\x05\x00'
8 b'\x05\x01\x00\x01\xac\xd9\x19\x0e\x00P'
10 b'\x05\x00\x00\x01\x00\x00\x00\x00\x00\x00'
12 b'GET /generate_204 HTTP/1.1\r\nHost: clients3.google.com\r\nUser-Agent: curl/7.64.1\r\nAccept: */*\r\n\r\n'
14 b'HTTP/1.1 204 No Content\r\nContent-Length: 0\r\nDate: Tue, 18 Aug 2020 06:50:44 GMT\r\n\r\n'
>>> from iofree.contrib import socks5
>>> socks5.Handshake.parse(packets[4].load, strict=False)
<Handshake(ver=5, methods=[<AuthMethod.no_auth: 0>, <AuthMethod.gssapi: 1>])>
>>> socks5.ServerSelection.parse(packets[6].load, strict=False)
<ServerSelection(ver=5, method=<AuthMethod.no_auth: 0>)>
>>> socks5.ClientRequest.parse(packets[8].load, strict=False)
<ClientRequest(ver=5, cmd=<Cmd.connect: 1>, rsv=0, addr=<Addr(atyp=1, host='172.217.25.14', port=80)>)>
>>> socks5.Reply.parse(packets[10].load, strict=False)
<Reply(ver=5, rep=<Rep.succeeded: 0>, rsv=0, bind_addr=<Addr(atyp=1, host='0.0.0.0', port=0)>)>
~~~

**Comment by hongyi-zhao** [comment]
Thanks a lot for your help. But, I still have some question on your above suggestion, especially, if I use scapy, can't scapy itself do this job for me? I mean, it's well known that scapy is a very powerful network tool, why must I combine these two tools for such a not so complicated job?

**Comment by guyingbo** [comment]
Yep, `scapy` is much powerful and `iofree` is mainly designed for protocol parsing but not for network handling. In this case you have to use some sort of network tools.
